[package]
name = "nvim-oxi"
version = "0.2.1"
authors = ["Riccardo Mazzarini <riccardo.mazzarini@pm.me>"]
edition = "2021"
rust-version = "1.62"
description = "Rust bindings to all things Neovim."
documentation = "https://docs.rs/nvim_oxi"
readme = "../../README.md"
repository = "https://github.com/noib3/nvim-oxi"
license = "MIT"
keywords = ["bindings", "neovim", "nvim"]

[package.metadata.docs.rs]
features = ["neovim-0-8", "libuv", "mlua", "test"]
rustdoc-args = ["--cfg", "docsrs"]

[features]
neovim-0-7 = ["nvim-types/neovim-0-7", "nvim-api/neovim-0-7"]
neovim-0-8 = ["nvim-types/neovim-0-8", "nvim-api/neovim-0-8"]
neovim-nightly = ["nvim-types/neovim-nightly", "nvim-api/neovim-nightly"]

libuv = ["libuv-bindings"]
mlua = ["dep:mlua"]
test = ["oxi-test"]

[dependencies]
libuv-bindings = { version = "0.2.0", path = "../libuv-bindings", optional = true }
luajit-bindings = { version = "0.2.0", path = "../luajit-bindings" }
nvim-api = { version = "0.2.0", path = "../nvim-api" }
nvim-types = { version = "0.2.0", path = "../nvim-types", features = ["serde"] }
oxi-module = { version = "0.2.0", path = "../oxi-module" }
oxi-test = { version = "0.2.0", path = "../oxi-test", optional = true }

mlua = { version = "0.8", optional = true }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

[dev-dependencies]
mlua = { version = "0.8", features = ["luajit", "module", "vendored"] }
tokio = { version = "1.0", features = ["full"] }

[[example]]
name = "api"
path = "../../examples/api.rs"
crate-type = ["cdylib"]

[[example]]
name = "calc"
path = "../../examples/calc.rs"
crate-type = ["cdylib"]

[[example]]
name = "libuv"
path = "../../examples/libuv.rs"
crate-type = ["cdylib"]
required-features = ["libuv"]

[[example]]
name = "mechanic"
path = "../../examples/mechanic.rs"
crate-type = ["cdylib"]

[[example]]
name = "mlua"
path = "../../examples/mlua.rs"
crate-type = ["cdylib"]
required-features = ["mlua"]
